<?php
return [
    'map' => [
        'camerounais-du-monde' => 31,
        'droit' => 30,
        'point-de-vue' => 30,
        'diaspora' => 34,
        'le-saviez-vous' => 35,
        'le-coin-sante' => 35,
        'francafrique' => 26,
        'liens-postcoloniaux' => 23,
        'francaiscamer' => 32,
        'fait-curieux' => 32,
        'libre-parole' => 33,
        'point-du-droit' => 33,
        'frananglais' => 29,
        'le-debat' => 27,
        'analyse' => 27,
        'tribune' => 25,
        'actualites' => 1,
        'musique' => 1,
        'livres' => 2,
        'people' => 5,
        'culture' => 6,
        'societe' => 11,
        'sante' => 13,
        'cinema' => 14,
        'insolite' => 15,
        'art' => 16,
        'economie' => 12,
        'religion' => 10,
        'politique' => 6,
        'sport' => 7,
        'allo-docteur' => 37,
        'geopolitique' => 38,
        'monde-pouvoir' => 36,
        'sans-tabou' => 36,
        'media' => 24,
        'evenements' => 22,
        'panafricanisme' => 41,
        'presidentielle-2025' => 40,
        'serail' => 39,
        'success-story' => 29,
    ],
];
