<?php

namespace App\Repositories;

use App\IRepository\IRubriqueRepository;
use App\Models\Rubrique;

class RubriqueRepository extends Repository implements IRubriqueRepository
{
    /**
     * @param $model
     */
    public function __construct(Rubrique $rubrique)
    {
        parent::__construct($rubrique);
    }

    /**
     * @param array $input
     * @return mixed
     */
    function create(array $input)
    {
        $input['rubrique']= strtoupper($input['rubrique']);
        return parent::create($input);
    }

    /**
     * @param $id
     * @return mixed
     */
    function delete($id)
    {
        return parent::delete($id);
    }

    /**
     * @param $id
     * @return mixed
     */
    function findById($id)
    {
        return parent::findById($id);
    }

    /**
     * @param array $input
     * @param $id
     * @return mixed
     */
    function update(array $input, $id)
    {
        $currentRubrique=$this->findById($id);
        $input['rubrique']= isset($input['rubrique'])? strtoupper($input['rubrique'])
            :$currentRubrique->rubrique;
        return parent::update($input, $id); // TODO: Change the autogenerated stub
    }

    /**
     * @return mixed
     */
    function index()
    {
        return Rubrique::orderBy('rubrique','asc')->get();
    }

    /**
     * @return mixed
     */
    function allRubrique()
    {
        return $this->index();
    }
}
